version: "3"

services:
  server:
    container_name: acala-height
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1020:1020"
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - network
    depends_on:
      - redis

  redis:
    image: redis
    container_name: price-redis
    restart: always
    networks:
      - network
    expose:
      - "6379"
networks:
  network:
    driver: bridge