version: "3"

services:
  server:
    container_name: acala-utils
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1020:1020"
    restart: always
    environment:
      NODE_ENV: production
    networks:
      - network
    depends_on:
      - redis
      - mongo
  
  redis:
    image: redis
    container_name: utils-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network
    expose:
      - "6379"
  
  mongo:
    image: mongo
    container_name: utils-mongo
    restart: always
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - network
    expose:
      - "27017"
networks:
  network:
    driver: bridge